# Generated by Django 5.0.3 on 2024-03-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RatingComment',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('book_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('comment', models.TextField()),
                ('comment_date', models.DateField()),
            ],
        ),
    ]
