# Generated by Django 5.0.2 on 2024-02-17 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('bookid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('isbn', models.CharField(blank=True, max_length=13, null=True, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('publicationyear', models.IntegerField(blank=True, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('stockquantity', models.IntegerField()),
                ('thumbnailurl', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'books',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cartitems',
            fields=[
                ('cartitemid', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
            ],
            options={
                'db_table': 'cartitems',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RatingsComments',
            fields=[
                ('ratingid', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('commentdate', models.DateTimeField()),
            ],
            options={
                'db_table': 'ratings_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shoppingcart',
            fields=[
                ('cartid', models.AutoField(primary_key=True, serialize=False)),
                ('dateadded', models.DateTimeField()),
            ],
            options={
                'db_table': 'shoppingcart',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('userid', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('joindate', models.DateTimeField()),
                ('address', models.TextField(blank=True, null=True)),
                ('phonenumber', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('wishlistid', models.AutoField(primary_key=True, serialize=False)),
                ('datecreated', models.DateTimeField()),
            ],
            options={
                'db_table': 'wishlist',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Wishlistitems',
            fields=[
                ('wishlistitemid', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'wishlistitems',
                'managed': False,
            },
        ),
    ]
