# Generated by Django 5.0.2 on 2024-02-21 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feature_Wishlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'managed': False, 'verbose_name': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='wishlistitems',
            options={'managed': False, 'verbose_name': 'Wishlist Item'},
        ),
    ]
