# Generated by Django 5.0.2 on 2024-03-09 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Feature_Wishlist', '0002_alter_books_options_alter_wishlistitems_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'managed': True, 'verbose_name': 'Book'},
        ),
        migrations.AlterModelOptions(
            name='cartitems',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='ratingscomments',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='wishlist',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='wishlistitems',
            options={'managed': True, 'verbose_name': 'Wishlist Item'},
        ),
    ]
